"""update group member roles

Revision ID: 363dca941ea9
Revises: 3d84ba4b49bb
Create Date: 2025-05-31 00:26:07.524814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '363dca941ea9'
down_revision: Union[str, None] = '3d84ba4b49bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('groups_leader_id_fkey', 'groups', type_='foreignkey')
    op.drop_column('groups', 'leader_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('leader_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('groups_leader_id_fkey', 'groups', 'users', ['leader_id'], ['id'])
    # ### end Alembic commands ###
