"""add todays_pnl to group

Revision ID: 3d84ba4b49bb
Revises: d13e69ff5cbb
Create Date: 2025-05-30 23:53:31.388237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d84ba4b49bb'
down_revision: Union[str, None] = 'd13e69ff5cbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('todays_pnl', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'todays_pnl')
    # ### end Alembic commands ###
