"""add_trade_mirroring_fields

Revision ID: 45d40759b82c
Revises: a82d769ae3b3
Create Date: 2025-06-05 00:30:43.935227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45d40759b82c'
down_revision: Union[str, None] = 'a82d769ae3b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('follower_id', sa.Integer(), nullable=True))
    op.add_column('trades', sa.Column('parent_trade_id', sa.Integer(), nullable=True))
    op.add_column('trades', sa.Column('last_price_update', sa.DateTime(), nullable=True))
    op.add_column('trades', sa.Column('executed_price', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('error_message', sa.Text(), nullable=True))
    op.alter_column('trades', 'leader_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('trades', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('trades', 'zerodha_order_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('trades', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('trades', 'trade_type',
               existing_type=postgresql.ENUM('REGULAR', 'CO', 'OCO', 'BRACKET', name='tradetype'),
               nullable=False)
    op.alter_column('trades', 'status',
               existing_type=postgresql.ENUM('OPEN', 'COMPLETE', 'CANCELLED', name='tradestatus'),
               nullable=False)
    op.alter_column('trades', 'expiry_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_foreign_key(None, 'trades', 'users', ['follower_id'], ['id'])
    op.create_foreign_key(None, 'trades', 'trades', ['parent_trade_id'], ['id'])
    op.drop_column('trades', 'last_updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('last_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.alter_column('trades', 'expiry_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('trades', 'status',
               existing_type=postgresql.ENUM('OPEN', 'COMPLETE', 'CANCELLED', name='tradestatus'),
               nullable=True)
    op.alter_column('trades', 'trade_type',
               existing_type=postgresql.ENUM('REGULAR', 'CO', 'OCO', 'BRACKET', name='tradetype'),
               nullable=True)
    op.alter_column('trades', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('trades', 'zerodha_order_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('trades', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('trades', 'leader_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('trades', 'error_message')
    op.drop_column('trades', 'executed_price')
    op.drop_column('trades', 'last_price_update')
    op.drop_column('trades', 'parent_trade_id')
    op.drop_column('trades', 'follower_id')
    # ### end Alembic commands ###
