"""add_trade_model_fields

Revision ID: 76e2808589be
Revises: 02ecdad887e2
Create Date: 2025-06-04 23:22:13.305956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76e2808589be'
down_revision: Union[str, None] = '02ecdad887e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('instrument_type', sa.Enum('EQUITY', 'OPTION', 'FUTURE', name='instrumenttype'), nullable=False))
    op.add_column('trades', sa.Column('strike_price', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('expiry_date', sa.Date(), nullable=True))
    op.add_column('trades', sa.Column('option_type', sa.String(), nullable=True))
    op.add_column('trades', sa.Column('current_market_price', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('last_updated_at', sa.DateTime(), nullable=True))
    op.add_column('trades', sa.Column('unrealized_pnl', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'unrealized_pnl')
    op.drop_column('trades', 'last_updated_at')
    op.drop_column('trades', 'current_market_price')
    op.drop_column('trades', 'option_type')
    op.drop_column('trades', 'expiry_date')
    op.drop_column('trades', 'strike_price')
    op.drop_column('trades', 'instrument_type')
    # ### end Alembic commands ###
